Feature db 85440 revisar ciclo de vida
BBVAEngineering/ember-cli-htmlbars-minifier pull request #5
Opened 2018-02-22 08:32 UTC by etarancon

- Package configured to launch the eslint comand to every js file.
- Contributing and license sections, bbva-eslint link and npm version tag added to README.md.
- .eslintrc file converted to js due to it's deprecated.

2018-04-17 14:44 UTC, josex2r requested changes

2018-04-17 14:44 UTC, josex2r commented on .travis.yml
>    - export DISPLAY=:99.0
This shouldn't be necessary

```
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
```

2018-04-17 15:03 UTC, etarancon commented on .travis.yml
>    - export DISPLAY=:99.0
done!!

2018-04-18 07:43 UTC, josex2r approved these changes

2018-04-18 07:48 UTC, merged